#Importing Libraries:

In [ ]:
import torch
import numpy as np

#Lists:

In [ ]:
list1D = [0, 1, 2, 5, 10, 100]
print(list1D)
print(type(list1D))
print(len(list1D))

list2D = [['a','b'], ['c','d','e'],['f']]
print(list2D)
print(len(list2D))
print(len(list2D[0]))

[0, 1, 2, 5, 10, 100]
<class 'list'>
6
[['a', 'b'], ['c', 'd', 'e'], ['f']]
3
2


#Numpy Arrays:

In [ ]:
npl1 = np.random.rand(2)
print(npl1)
print(type(npl1))
print(npl1.dtype)
print(npl1.shape)

npl2 = np.random.rand(3,4) #Prints a 3x4 array b/w 0 & 1
print(npl2)
print(npl2.shape)

print(np.random.randint(1, 11, 3)) #Prints an array of 3 numbers b/w 1 to 10

[0.908154   0.50777715]
<class 'numpy.ndarray'>
float64
(2,)
[[0.548819   0.60679411 0.78114053 0.24548489]
 [0.00968091 0.37380942 0.31881762 0.59915846]
 [0.28076064 0.80123238 0.80800237 0.76171079]]
(3, 4)
[1 1 1]


#Tensors:

In [ ]:
t = torch.empty(2, 3) #Initializes a 2x3 empty tensor
print(t)

In [ ]:
t1 = torch.rand(2) #Creates a tensor of length 2 with random numbers b/w 0 & 1
print(t1)
print(type(t1))

t2 = torch.rand(2, 3)
print(t2)

In [ ]:
t3 = torch.zeros(2,3,4) #Creates a 2x3x4 tensor with zeros
print(t3)
print(type(t3))
print(t3.dtype)
print(t3.shape)

t4 = torch.ones(2,3, dtype=torch.int) #Creates a 2x3 tensor with ones
print(t4)
print(t4.dtype)
print(type(t4))
print(t4.size())

In [ ]:
#Create a tensor from np array
t5 = torch.tensor(npl2)
print(t5)