#Saving and Loading Model

##Importing Libraries:

In [1]:
import torch
import torch.nn as nn

##Option 1 - Lazy Method:

- torch.save() can use tensors, models or any dictionary as parameter for saving

- python uses pickle module to serialize the objects and saves them

- the result is serialized and not human readable

- to load model: model = torch.load(PATH)


In [2]:
class Model(nn.Module):

  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)

  def forward(self, x):
    y_pred = torch.sigmoid(self.Linear(x))
    return y_pred

In [3]:
model = Model(6)

#model training....

In [4]:
#inspecting model parameters
print("Model Parameters:")
for param in model.parameters(): #weights and bias
  print(param)

Model Parameters:
Parameter containing:
tensor([[ 0.1045, -0.1647, -0.2671,  0.0191, -0.0509,  0.2351]],
       requires_grad=True)
Parameter containing:
tensor([-0.0604], requires_grad=True)


In [5]:
FILE = "model.pth" #filepath variable
#.pth is short for pytorch

In [6]:
torch.save(model, FILE)

In [7]:
#load model
model = torch.load(FILE)
model.eval()

<ipython-input-7-c36fd118b5d2>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(FILE)


Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [8]:
#inspecting loaded model parameters
print("Loaded Model Parameters:")
for param in model.parameters(): #weights and bias
  print(param)

Loaded Model Parameters:
Parameter containing:
tensor([[ 0.1045, -0.1647, -0.2671,  0.0191, -0.0509,  0.2351]],
       requires_grad=True)
Parameter containing:
tensor([-0.0604], requires_grad=True)


##Option 2 - State Dict Method: (Recommended)

- Recommended method for saving the model and using it later for inference

- only saves parameters of the model

- torch.save(model.state_dict(), PATH)

- To load model: model.load_state_dict(torch.load(PATH))

In [9]:
class Model(nn.Module):

  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)

  def forward(self, x):
    y_pred = torch.sigmoid(self.Linear(x))
    return y_pred

In [10]:
model = Model(6)

#model training....

In [11]:
#inspecting model parameters
print("Model Parameters:")
for param in model.parameters(): #weights and bias
  print(param)

Model Parameters:
Parameter containing:
tensor([[ 0.3293,  0.2730,  0.2050,  0.0291, -0.3129, -0.2614]],
       requires_grad=True)
Parameter containing:
tensor([0.0447], requires_grad=True)


In [12]:
FILE = "model.pth" #filepath variable
#.pth is short for pytorch

In [13]:
#save model parameters

torch.save(model.state_dict(), FILE)

In [14]:
print("Model State Dict: ", model.state_dict())

Model State Dict:  OrderedDict([('linear.weight', tensor([[ 0.3293,  0.2730,  0.2050,  0.0291, -0.3129, -0.2614]])), ('linear.bias', tensor([0.0447]))])


In [16]:
#load model parameters

loaded_model = Model(6) #initializing model
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

<ipython-input-16-82d44158b2c8>:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load(FILE))


Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [17]:
#inspecting loaded model parameters
print("Loaded Model Parameters:")
for param in model.parameters(): #weights and bias
  print(param)

Loaded Model Parameters:
Parameter containing:
tensor([[ 0.3293,  0.2730,  0.2050,  0.0291, -0.3129, -0.2614]],
       requires_grad=True)
Parameter containing:
tensor([0.0447], requires_grad=True)


In [18]:
print("Loaded Model State Dict: ", loaded_model.state_dict())

Loaded Model State Dict:  OrderedDict([('linear.weight', tensor([[ 0.3293,  0.2730,  0.2050,  0.0291, -0.3129, -0.2614]])), ('linear.bias', tensor([0.0447]))])


##Saving Checkpoint During Training:

In [19]:
class Model(nn.Module):

  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)

  def forward(self, x):
    y_pred = torch.sigmoid(self.Linear(x))
    return y_pred

In [20]:
model = Model(6)

#model training....

In [21]:
learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [22]:
print("Optimizer State Dict: ",optimizer.state_dict())

Optimizer State Dict:  {'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


In [23]:
#creating a dictionary:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}

In [24]:
#saving checkpoint
torch.save(checkpoint, "checkpoint1.pth")

In [25]:
#loading checkpoint
loaded_checkpoint = torch.load("checkpoint1.pth")

<ipython-input-25-a2e6e657fa2a>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_checkpoint = torch.load("checkpoint1.pth")


In [27]:
epoch = loaded_checkpoint["epoch"]

#initializing model and optimizer
model = Model(6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)

model.load_state_dict(loaded_checkpoint["model_state"])
optimizer.load_state_dict(loaded_checkpoint["optim_state"])

#continue model training...

In [28]:
print("Loaded Optimizer State Dict: ",optimizer.state_dict())

Loaded Optimizer State Dict:  {'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


##Using GPU:

###Option 1 - Save on GPU, Load on CPU:

In [ ]:
#Option 1 - Save on GPU, Load on CPU
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), FILE)

In [ ]:
device = torch.device('cpu')
model = Model(6)
model.load_state_dict(torch.load(FILE, map_location=(device)))

### Option 2 - Save & Load on GPU

In [ ]:
# Option 2 - Save & Load on GPU
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), FILE)

In [ ]:
model = Model(6)
model.load_state_dict(torch.load(FILE))
model.to(device)

###Option 3 - Save on CPU, Load on GPU

In [ ]:
#Option 3 - Save on GPU, Load on CPU
torch.save(model.state_dict(), FILE)

In [ ]:
device = torch.device('cuda')
model = Model(6)
model.load_state_dict(torch.load(FILE, map_location=("cuda:0"))) #choose GPU device number
model.to(device)